<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Gamma.RoboKP.Domain\Gamma.RoboKP.Domain.csproj" />
      <ProjectReference Include="..\Gamma.RoboKP.Infrastructure\Gamma.RoboKP.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="iTextSharp" Version="5.5.13.4" />
      <PackageReference Include="Mapster" Version="7.4.0" />
      <PackageReference Include="Microsoft.Office.Interop.PowerPoint" Version="15.0.4420.1018" />
      <PackageReference Include="NETCore.MailKit" Version="2.1.0" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

</Project>
